<?php

/**
 * Implements hook_user_operations().
 */
function mass_reset_user_operations() {
  $operations = array(
    'reset' => array(
      'label' => t('Reset the selected user passwords and send password reset email'),
      'callback' => 'mass_reset_send_password_reset_email',
    ),
    'resetnomail' => array(
      'label' => t('Reset the selected user passwords, no reset email'),
      'callback' => 'mass_reset_send_password_reset_noemail',
    ),
  );
  return $operations;
}

/**
 * Implements hook_action_info().
 */
function mass_reset_action_info() {
  return array(
    'mass_reset_send_password_reset_email_user_action' => array(
      'description' => t('Reset user password and send password reset email'),
      'type' => 'user',
      'configurable' => FALSE,
      'hooks' => array(),
    ),
    'mass_reset_send_password_reset_noemail_user_action' => array(
      'description' => t('Reset user password, no reset email'),
      'type' => 'user',
      'configurable' => FALSE,
      'hooks' => array(),
    ),
  );
}

/**
 * Operations callback. Sets password blank and sends reset emali.
*/
function mass_reset_send_password_reset_email($accounts) {
  foreach ($accounts as $uid) {
    if ($uid && $uid > 1) {
      // set random password for user
      $randpass = user_password();
      db_query("UPDATE {users} SET pass = '%s' WHERE uid = %d", $randpass, $uid);
      $user = user_load(array('uid' => (int)$uid));
      // send password reset email
      global $language;
      _user_mail_notify('password_reset', $user, $language);
      // destroy all user sessions
      sess_destroy_uid($uid);
      watchdog('action', 'Sent password reset email for user %name.', array('%name' => check_plain($user->name)));
    }
  }
}

/**
 * Operations callback. Sets password blank but does not send email.
*/
function mass_reset_send_password_reset_noemail($accounts) {
  foreach ($accounts as $uid) {
    if ($uid && $uid > 1) {
      // set random password for user
      $randpass = user_password();
      db_query("UPDATE {users} SET pass = '%s' WHERE uid = %d", $randpass, $uid);
      $user = user_load(array('uid' => (int)$uid));
      // destroy all user sessions
      sess_destroy_uid($uid);
      watchdog('action', 'Sent password reset email for user %name.', array('%name' => check_plain($user->name)));
    }
  }
}

/**
 * Implementation of a Drupal action.
 * Reset a user's password and sends the user a password reset email.
 */
function mass_reset_send_password_reset_email_user_action(&$object, $context = array()) {
  if (isset($object->uid)) {
    $uid = $object->uid;
  }
  elseif (isset($context['uid'])) {
    $uid = $context['uid'];
  }
  else {
    // something went wrong
    $uid = NULL;
  }
  if ($uid && $uid > 1) {
    // set random password for user
    $randpass = user_password();
    db_query("UPDATE {users} SET pass = '%s' WHERE uid = %d", $randpass, $uid);
    $user = user_load($uid);
    // send password reset email
    global $language;
    _user_mail_notify('password_reset', $user, $language);
    // destroy all user sessions
    sess_destroy_uid($uid);
    watchdog('action', 'Sent password reset email for user %name.', array('%name' => check_plain($user->name)));
  }
}

/**
 * Implementation of a Drupal action.
 * Resets a user password but doesn't send email.
 */
function mass_reset_send_password_reset_noemail_user_action(&$object, $context = array()) {
  if (isset($object->uid)) {
    $uid = $object->uid;
  }
  elseif (isset($context['uid'])) {
    $uid = $context['uid'];
  }
  else {
    // something went wrong
    $uid = NULL;
  }
  if ($uid && $uid > 1) {
    // set random password for user
    $randpass = user_password();
    db_query("UPDATE {users} SET pass = '%s' WHERE uid = %d", $randpass, $uid);
    $user = user_load($uid);
    // destroy all user sessions
    sess_destroy_uid($uid);
    watchdog('action', 'Sent password reset email for user %name.', array('%name' => check_plain($user->name)));
  }
}